env:
  - NODE_VERSION=4 SCRIPT=lint
  - NODE_VERSION=4 SCRIPT=test
  - NODE_VERSION=5 SCRIPT=test
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: NODE_VERSION=4 SCRIPT=lint

script:
  - npm run-script $SCRIPT

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash; fi
  - source ~/.nvm/nvm-exec
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
