language: node_js

node_js:
  - "5.0"
  - "4.0"

os:
  - linux
  - osx

script:
  - npm run-script $SCRIPT

before_install:
  - npm config set spin false
  - npm config set progress false

install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
