language: node_js

node_js:
  - "5.0"
  - "4.0"

env:
  - NODE_VERSION=4 SCRIPT=lint
  - NODE_VERSION=4 SCRIPT=test
  - NODE_VERSION=5 SCRIPT=test
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: NODE_VERSION=4 SCRIPT=lint

script:
  - npm run-script $SCRIPT

install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
